### ISSUE TITLE
Can this be made to work with coc-nvim?

### ISSUE THREAD

**Issue by rickyelopez** [folke/lsp-trouble.nvim#12]
From what I can gather from the Readme, it looks like this only works with the neovim LSP client? Any chance this could be expanded to work with coc-nvim (probably other popular LSP clients too?)

I could be totally misunderstanding how this works though...

**Comment by folke** [comment]
Theoretically it probably can be integrated, but it's not something that I plan to implement soon. PR always welcome :)

**Comment by rickyelopez** [comment]
Well I have no idea what I'm doing, but if I get some time I'll take a look :)

**Comment by folke** [comment]
@rickyelopez I just released a big update with support for quickfix and location lists. This way you should be able to make it work with Coc. Let me know if it works out this way!

**Comment by rickyelopez** [comment]
Cool, I'll give it a shot, thanks!

**Comment by folke** [comment]
Depending on where coc pushes diagnostics, you'll need to open LspTrouble with quickfix or loclist as argument.

**Comment by rickyelopez** [comment]
Yup just found that, appears to work great! I'll keep evaluating and let you know. Maybe this belongs in the README?

**Comment by folke** [comment]
Good point, I will add something about that

**Comment by macintacos** [comment]
@rickyelopez were you able to figure out how to integrate it properly with something like https://github.com/iamcco/coc-diagnostic? Struggling how to figure out the handoff between CoC and Trouble - I can figure out how to send individual items to Trouble, just not the full list of errors/warnings in a project or buffer 🤔

**Comment by piersolenski** [comment]
@folke @macintacos @rickyelopez would love to know how to get this working with CoC too!

**Comment by shift-d** [comment]
I am struggling with this issue too, but don't want to duplicate. @rickyelopez , how you did solve this problem?

**Comment by folke** [comment]
have you tried opening trouble wil loclist or quickfix?

**Comment by rickyelopez** [comment]
Sorry I didn't answer previous pings, been very busy. I haven't been using this a ton so can't say for sure how well this is working, but here's what I had to do to get it working:

In `coc-settings.json`:
```
    "clangd.semanticHighlighting": true,
    "diagnostic.locationlistUpdate": true,
    "diagnostic.refreshOnInsertMode": true
```

My `lsptrouble.vim`:
```
lua << EOF
require("trouble").setup {
    height = 10, -- height of the trouble list
    icons = true, -- use devicons for filenames
    mode = "loclist", -- "lsp_workspace_diagnostics", "lsp_document_diagnostics", "quickfix", "lsp_references", "loclist"
    fold_open = "", -- icon used for open folds
    fold_closed = "", -- icon used for closed folds
    action_keys = { -- key mappings for actions in the trouble list
        close = "q", -- close the list
        cancel = "<esc>", -- cancel the preview and get back to your last window / buffer / cursor
        refresh = "r", -- manually refresh
        jump = {"<cr>", "<tab>"}, -- jump to the diagnostic or open / close folds
        jump_close = {"o"}, -- jump to the diagnostic and close the list
        toggle_mode = "m", -- toggle between "workspace" and "document" diagnostics mode
        toggle_preview = "P", -- toggle auto_preview
        hover = "K", -- opens a small poup with the full multiline message
        preview = "p", -- preview the diagnostic location
        close_folds = {"zM", "zm"}, -- close all folds
        open_folds = {"zR", "zr"}, -- open all folds
        toggle_fold = {"zA", "za"}, -- toggle fold of current file
        previous = "k", -- preview item
        next = "j" -- next item
    },
    indent_lines = true, -- add an indent guide below the fold icons
    auto_open = false, -- automatically open the list when you have diagnostics
    auto_close = false, -- automatically close the list when you have no diagnostics
    auto_preview = true, -- automatyically preview the location of the diagnostic. <esc> to close preview and go back to last window
    auto_fold = false, -- automatically fold a file trouble list at creation
    signs = {
        -- icons / text used for a diagnostic
        error = "",
        warning = "",
        hint = "",
        information = "",
        other = "﫠"
    },
    use_lsp_diagnostic_signs = false -- enabling this will use the signs defined in your lsp client
}
EOF

nnoremap <leader>xx <cmd>LspTroubleToggle<cr>
```

Like I said, this seems to be working, but I haven't used it a ton. Let me know if you find any improvements :)

**Comment by piersolenski** [comment]
I've tried this and initially, nothing shows. However, if I run `:CocDiagnostics`, then toggle Trouble again, suddenly then will show. It won't update again until I run `:CocDiagnostics` again 😭

**Comment by piersolenski** [comment]
Well I got it kind of working in the end by [sending my diagnostics to ALE](https://github.com/dense-analysis/ale#faq-coc-nvim).

In order to use the `quickfix` list specifically, you can use the following additional settings:

```
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
```

and

```
require("trouble").setup {  mode = "quickfix" }
```

This doesn't seem to work with the `auto_open`/`auto_close` settings but I can live without that for now!

**Comment by arafatamim** [comment]
@piersolenski I think a better solution would be doing something like this:
```vim
nmap <silent> gL <cmd>call coc#rpc#request('fillDiagnostics', [bufnr('%')])<CR><cmd>Trouble loclist<CR>`
```

**Comment by rickyelopez** [comment]
That seems to work great! Thanks for that!

**Comment by arafatamim** [comment]
PS, if anyone's interested, I've created a fork of this project at [arafatamim/trouble.nvim](https://github.com/arafatamim/trouble.nvim), with support for LSP-equivalent actions like diagnostics, references, implementations, etc for CoC.
