### ISSUE TITLE
No errors shown in list

### ISSUE THREAD

**Issue by max397574** [folke/lsp-trouble.nvim#14]
I installed lsp-trouble.nvim with Vim-Plug
nvim version: 0.5 nightly
I use your tokyonight colorscheme

I created a file to test the LspTrouble.
Then I used :LspTroubleOpen

![Screen Shot 2021-04-29 at 14 59 46](https://user-images.githubusercontent.com/81827001/116556058-57e8d100-a8fd-11eb-8662-eb8220241b57.png)

The list is just empty even though, there are errors

**Comment by folke** [comment]
Are these errors diagnostics from the builtin lsp client? Or is that something like ALE?

**Comment by max397574** [comment]
I have ALE
Should I deactivate it?

**Comment by folke** [comment]
That;s not it, but I wonder if those errors you are seeing are coming from ALE and are not lsp diagnostics.

**Comment by max397574** [comment]
so should I try deactivating it?

**Comment by folke** [comment]
To make sure they are from lsp, do;
```vim
:lua vim.lsp.diagnostic.set_loclist()
```
That should show those errors in your quicklist

**Comment by max397574** [comment]
![Screen Shot 2021-04-29 at 15 38 48](https://user-images.githubusercontent.com/81827001/116559701-ff1b3780-a900-11eb-94da-4b54e83434ce.png)

Now it looks different but still no errors shown

**Comment by folke** [comment]
That means that those errors are not coming from LSP.
Closing this as it's an issue with your lsp setup. Nothing to do with trouble.

Please follow the guide at https://github.com/neovim/nvim-lspconfig to get it working

**Comment by max397574** [comment]
https://www.reddit.com/r/neovim/comments/n3rary/trouble_just_pushed_a_big_update_with_support_for/

is this still a problem?

**Comment by folke** [comment]
With ALE you can push your errors to the quickfix and/or loclist, so try one of the commands below:
* `LspTrouble quickfix`
* `LspTrouble loclist`

That should work, although I haven't tested it specifically with ALE :)
