### ISSUE TITLE
Option to auto-close error-list after confirming a jump

### ISSUE THREAD

**Issue by elkowar** [folke/lsp-trouble.nvim#15]
I'd love to have the error list automatically close once I jump to one of the errors (i.e. hit enter). Currently, if i want to close it again after jumping, i have to `<C-w><C-w>q`, which is rather anoying. having a `close_on_jump` option would be nice, and is the main thing keeping me from using this right now

**Comment by folke** [comment]
Good idea! I'll add it somewhere tomorrow

**Comment by folke** [comment]
I just added this.

There's a new action `jump_close` that is bind to `o` by default.

You can rebind it to `<cr>` or something else and change the default of `jump` to any other key.

Thanks again for the suggestion!

**Comment by elkowar** [comment]
Amazing! Thanks a ton!
