### ISSUE TITLE
Can't configure signs

### ISSUE THREAD

**Issue by ReubenM** [folke/lsp-trouble.nvim#16]
I've tried different symbols and plain text. Doesn't seem to make any difference. The action_keys config works.
```
use {
  'folke/lsp-trouble.nvim',
  requires = {
    'kyazdani42/nvim-web-devicons'
  },
  config = function()
    require( 'trouble' ).setup {
      action_keys = {
        toggle_fold = { '<Space>' }
      },
      signs = {
        error = ' ',
        warning = ' ',
        hint = ' ',
        information = ' '
      }
    }
  end
}

**Comment by folke** [comment]
That's odd, can you post a screenshot?

**Comment by ReubenM** [comment]
![Screenshot_20210429_173133](https://user-images.githubusercontent.com/45847/116626618-2aa61e00-a911-11eb-9c78-eef9ca925600.png)

**Comment by folke** [comment]
The signs are there in the list on the left 😄 

You probably mean the signs in the editor? Trouble doesn't change those. I use [lsp-saga](https://github.com/glepnir/lspsaga.nvim) for that, but you can probably also easily define them yourself using the lsp API

**Comment by ReubenM** [comment]
No I mean changing the signs. Those are same as the default if I don't configure any signs. I can't set them to anything else.

**Comment by ReubenM** [comment]
Figured out what was going on:

TIL: If using Packer and setting up the config in-line with Packer's 'use' method, all the config gets collected into Packer's compiled output. So when setting it config up that way and making changes, you need to re-compile Packer's plugins for it to take effect. Was not aware Packer's compiler would include config info, but then again I had not set any nvim extension config in-line with the 'use' method until now. 

Splitting the config out to a separate call within the init.lua avoids having the config getting pulled into Packer's compiler.

**Comment by folke** [comment]
Glad you got it working!

**Comment by LuisxSullivaN** [comment]
> The signs are there in the list on the left 
> 
> You probably mean the signs in the editor? Trouble doesn't change those. I use [lsp-saga](https://github.com/glepnir/lspsaga.nvim) for that, but you can probably also easily define them yourself using the lsp API with
> `vim.lsp.diagnostic.set_signs()`

@folke can you elaborate more on set those signs? maybe an example or your config; either for lsp saga or through vim.lsp.diagnostic.set_signs(), I tried with the latter but simply don't know how to get it to working:-(

**Comment by folke** [comment]
@LuisxSullivaN you can check the lspconfig wiki. That's the exact code I use https://github.com/nanotee/nvim-lua-guide#learning-lua
