### ISSUE TITLE
Make list UI more generically usable

### ISSUE THREAD

**Issue by elkowar** [folke/lsp-trouble.nvim#17]
Currently, this is one of the, if not _the_ best UIs for a location-jump list interface. Especially once #15 is implemented, the UX here will be pretty much perfect!

Given that fact, I'd love to use the same UI in other places, too - such as a list references menu, stuff like that.

It would be amazing if it was possible to provide a more generic API for the list UI that can be used from outside of the plugin (such that I could manually implement this as my find-references provider, too), and, optimally, if this would just support these other use-cases out of the box.

Thanks for making an amazing plugin!

**Comment by folke** [comment]
Yeah, I've been thinking about that too.
Would be good to make it extensible and have providers for data in the last.

Some interesting ones:
 * lsp related ones as you mention like finding references etc
 * quickfix & loclists (Coc and ALE would then probably work as well)

Thank you for the suggestion. I'll see if I can implement something like this!

**Comment by elkowar** [comment]
Just making it a general quickfix & loclist UI would be brilliant! That + more LSP integration + a comfy lua api would be...... 💦

**Comment by folke** [comment]
I just pushed a big update with support for lsp references, quicklists and loclists.

Let me know what you think!

**Comment by elkowar** [comment]
This is really nice! Thanks a ton! I guess we can close this!
