### ISSUE TITLE
Turn a window into the trouble list

### ISSUE THREAD

**Issue by Julian** [folke/lsp-trouble.nvim#18]
Hi. I've spent minimal time with trouble so far, so apologies if this is somewhere I haven't found yet.

I want a way to turn an existing (empty) buffer *into* the trouble list. (Ideally I'd love to also have trouble use *part* of a buffer that is also being used for other things, but that I assume is more complex).

Does at least the former exist? What I see so far just looks like allowing trouble to do the split itself via `LspTroubleOpen/Toggle`, but I haven't fully read through the Lua API yet.

And thanks!

**Comment by folke** [comment]
It's not meant to be used like this. Trouble needs to fully own it's window and buffer to work properly. Even when you open a new buffer inside the Trouble window, we break out the new buffer to another window instead.

Closing this, as this is out of the scope of this project.
