### ISSUE TITLE
LSP throws error with fix available but quickfix toggle is empty

### ISSUE THREAD

**Issue by vinicius507** [folke/lsp-trouble.nvim#19]
I'm using neovim built-in LSP and, when it has an error with fix available, the quickfix toggle is empty.

Screenshot:
![image](https://user-images.githubusercontent.com/6608056/116925508-a49b1780-ac2f-11eb-898c-acf345bab876.png)

**Comment by folke** [comment]
Did you check the loclist? Does the regular qflist or loclist show that error?

**Comment by folke** [comment]
Sorry, my bad. Built-in lsp should show under lsp_workspace_diagnostics. This is the default

**Comment by vinicius507** [comment]
`loclist` does is empty. `lsp_worskpace_diagnostics` is not.
![image](https://user-images.githubusercontent.com/6608056/116926374-aaddc380-ac30-11eb-80ad-756eff7d2da3.png)

**Comment by folke** [comment]
So it all works as it should then? `lsp_workspace_diagnostics` and `lsp_document_diagnostics` show diagnostics from the builtin LSP client.

`quickfix` is to show the contents of the `qflist`, which has nothing to do with LSP

**Comment by folke** [comment]
This is the quickfix list: https://neovim.io/doc/user/quickfix.html

**Comment by vinicius507** [comment]
Oh, thanks! I thought it was a bug or some config that was missing :)
Thank you, closing now.

**Comment by folke** [comment]
No problem :)
