### ISSUE TITLE
No Highlighting When Jumping to Diagnostics with auto_preview off

### ISSUE THREAD

**Issue by fdschmidt93** [folke/lsp-trouble.nvim#2]
Hi there!

Very cool plugin - happy to see you've borrowed from the telescope diagnostics code (as I see some of my comments in the code base) :) glad you've found it useful!

One thing I noticed when playing around with it with these settings

```lua
require("trouble").setup {
  use_lsp_diagnostic_signs = true,
  auto_preview = false,
}
```
unlike with auto previewing, highlighting (= tree-sitter) does not attach to the buffer when jumping to the diagnostic as can be seen in the video.

https://user-images.githubusercontent.com/39233597/115768894-32af0c80-a3ab-11eb-8a8c-c876e16c3bd2.mp4

I was able to reproduce this issue with a minimal config that only loads my `nvim-treesitter` config, my `nvim-lsp` config and `LSP Trouble`

From the initial looks of it, in my scenario [vim.cmd "e"](https://github.com/folke/lsp-trouble.nvim/blob/0ad97fb67b21579729090214cbb3bce78fd153b7/lua/trouble/view.lua#L287) is skipped? I'm happy to further explore the code base and see if I can submit a PR but probably won't have time before Sunday evening.

**Comment by folke** [comment]
I'll add in a note that some of that code was based off Telescope :) Great project!

I know what's happening here. I'll see if I can fix it. Thank you for reporting!

**Comment by fdschmidt93** [comment]
Sure thing!

No worries, all open source :)

**Comment by folke** [comment]
Should be fixed now. I had been struggling to get unlisted buffer opened by the LSP Diagnostics to render properly and added some weird code to tackle it.

Finally found the original problem with that: `nvim_win_set_buf` has no side effects, so fix was to do `win.cmd "buffer ..."` instead.

That triggered another issue with nested loading of the preview window and updates in the renderer.

But everything should be working as expected now. Let me know if you have any more issues!

**Comment by fdschmidt93** [comment]
Works like a charm now, thanks!
