### ISSUE TITLE
Cursor position outside buffer (telescope into qfix)

### ISSUE THREAD

**Issue by aserowy** [folke/lsp-trouble.nvim#22]
First things first: YOU ARE AWESOME! Ty for your work!

Currently my workflow involves telescoping into quickfix. With trouble ill get lua exceptions, because telescope adds files with position [0, 0] to qfix.

![image](https://user-images.githubusercontent.com/8199164/116967941-ba522080-acb3-11eb-8b2f-2bd6e9853e0d.png)

After navigating on one entry with preview set to true, nvim fires:

![image](https://user-images.githubusercontent.com/8199164/116967976-d655c200-acb3-11eb-8d65-a730d12f7bc9.png)

**Comment by folke** [comment]
I just fixed this.

Also be sure to check out the [telescope integration](https://github.com/folke/lsp-trouble.nvim#telescope) to send results directly to **Trouble**

**Comment by aserowy** [comment]
cool! Yaeh, but i love cdo :D and col n' stuff

Ty for the fast response! Replaced qfix plugins with yours :D

**Comment by folke** [comment]
Great, thanks!
