### ISSUE TITLE
Highlight group for EndOfBuffer

### ISSUE THREAD

**Issue by akinsho** [folke/lsp-trouble.nvim#23]
Hi 👋🏾 ,

I just started customising my `LspTroubleNormal` background and noticed that it doesn't include the `EndOfBuffer` highlight so things looks like this.

![image](https://user-images.githubusercontent.com/22454918/117335698-55552100-ae93-11eb-8128-6a86dd530dbe.png)

The first line is the darkened highlight and the bottom is the `EndOfBuffer`. I think it should default link to `LspTroubleNormal` so it would be something like.

`setlocal winhighlight=Normal:LspTroubleNormal,EndOfBuffer:LspTroubleNormal,SignColumn:LspTroubleNormal`

This way a user can change the color of the full window not just part of it.

**Comment by folke** [comment]
Are you sure this is the issue here?

If I set the bg to red, the full window gets the bg color.

![image](https://user-images.githubusercontent.com/292349/117336423-08e8f180-ae51-11eb-90d0-863c64b634a5.png)

**Comment by folke** [comment]
You probably changed the LspTroubleText to a different bg than LspTroubleNormal?

**Comment by folke** [comment]
That's probably not it. Is it possible something else has changed the `winhighlight` option for the **trouble** window?

What does `setlocal winhilight?` give?

`setlocal winhighlight=Normal:LspTroubleNormal` should be enough.

**Comment by folke** [comment]
Nevermind. You're right. My theme doesn't set a bg for `EndOfBuffer`, so for me it's working.

I'll fix it. Thanks!

**Comment by folke** [comment]
it doesn't just work like that, since then the `~` at the end of buffer will get a foreground color, making it worse.

**Comment by folke** [comment]
Can fix that too with `setlocal fcs=eob:\ ` :)

**Comment by folke** [comment]
Fixed. Can you check?

**Comment by akinsho** [comment]
@folke awesome 👍🏾 yep that's fixed it 🚀
