### ISSUE TITLE
Workspace diagnostics only includes open buffers

### ISSUE THREAD

**Issue by disrupted** [folke/lsp-trouble.nvim#26]
I can't figure out how to get all workspace diagnostics to show up.

I have [lsp_extensions.nvim](https://github.com/nvim-lua/lsp_extensions.nvim) installed and overridden the `publishDiagnostics` handler in my config like so:

```lua
vim.lsp.handlers['textDocument/publishDiagnostics'] =
    vim.lsp.with(require('lsp_extensions.workspace.diagnostic').handler, {
        underline = false,
        signs = true,
        update_in_insert = false -- delay update
    })
```

When I run

```lua
:lua require('lsp_extensions.workspace.diagnostic').set_qf_list()
```

the quickfix list contains all diagnostics of files in the workspace. However when I run

```
:LspTroubleToggle lsp_workspace_diagnostics
```

it <strike>is empty</strike>. update: I actually just figured out it only shows diagnostics of currently open buffers.

How can I configure Trouble to pick up all workspace diagnostics?

**Comment by folke** [comment]
A couple of days ago, I apparently switched up the "document" with "workspace" diagnostics, so `lsp_workspace_diagnostics` actually showed those for the document only and vice versa.

This should now be fixed. Sorry about that

**Comment by disrupted** [comment]
Thanks, it's working now.

**Comment by harrysolovay** [comment]
I'm running into this same issue. I also have `nvim-lua/lsp_extensions.nvim` installed. I'm setting the callback as follows:

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] =
    vim.lsp.with(
    require("lsp_extensions.workspace.diagnostic").handler,
    {
        underline = false,
        signs = true,
        update_in_insert = true
    }
)
```

Calling `:LspTroubleToggle lsp_workspace_diagnostics` still only shows diagnostics for the current buffer :/

Any advice would be greatly appreciated! Thank you!

**Comment by rphuber** [comment]
can we reopen this?  I am getting the same behavior as well.  It is only showing diagnostics from files open in buffers and not the workspace.  or perhaps I am misunderstanding how workspace works?  any help  will be appreciated.  Thanks!

**Comment by disrupted** [comment]
@rphuber which language server? With Pyright, which I use most, workspace diagnostics are working. Perhaps it's simply not supported by your LS.

**Comment by artemave** [comment]
This plugin does workspace diagnostics https://github.com/artemave/workspace-diagnostics.nvim

**Comment by Pandoks** [comment]
> This plugin does workspace diagnostics https://github.com/artemave/workspace-diagnostics.nvim

We need this merged into Trouble istg. idk why this isn't talked about more
