### ISSUE TITLE
Error on opening Trouble if devicons is not installed

### ISSUE THREAD

**Issue by ChrisAmelia** [folke/lsp-trouble.nvim#3]
The following message appears:

> E5108: Error executing lua ...ack/packer/opt/lsp-trouble.nvim/lua/trouble/renderer.lua:13: module 'nvim-web-devicons' not found:                                                                                                
        no field package.preload['nvim-web-devicons']

**Comment by folke** [comment]
Fixed in https://github.com/folke/lsp-trouble.nvim/commit/7aabea5cca2d51ba5432c988fe84ff9d3644637a

Thank you for reporting!
