### ISSUE TITLE
Jump to location broke on modified buffers

### ISSUE THREAD

**Issue by ii14** [folke/lsp-trouble.nvim#5]
When file is modified and I'm pressing Enter on a diagnostic to jump to it, it throws an error instead:

`E5108: Error executing lua ...share/nvim/plugged/lsp-trouble.nvim/lua/trouble/view.lua:291: Vim(edit):E37: No write since last change (add ! to override)`

https://github.com/folke/lsp-trouble.nvim/blob/b20a7844a035cf6795270db575ad8c4db2a774c9/lua/trouble/view.lua#L291

**Comment by folke** [comment]
Damn, good catch!

I fixed an issue last night that introduced this.

Can you check if all works as expected now?

**Comment by ii14** [comment]
Seems to work :+1:
