### ISSUE TITLE
Jumping fails and throws error if file hasn't been saved

### ISSUE THREAD

**Issue by rorj** [folke/lsp-trouble.nvim#6]
`E5108: Error executing lua .../pack/packer/start/lsp-trouble.nvim/lua/trouble/view.lua:291: Vim(edit):E37: No write since last change (add ! to override)`

Commenting this line out fixes the issue.

https://github.com/folke/lsp-trouble.nvim/blob/751d4de754d877a1ffa376c7e2f4208082cfde1c/lua/trouble/view.lua#L291

**Comment by folke** [comment]
Damn, good catch!

I fixed an issue last night that introduced this.

Can you check if all works as expected now?

**Comment by rorj** [comment]
Yes, it's fixed now. Thanks.
